apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.deployment_name }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.deployment_name }}
  replicas:  {{ .replicas }} 
  template: 
    metadata:
      labels:
        app: {{ .Values.deployment_name }}
    spec:
      containers:
      - name: {{ .Values.deployment_name }}
        image: docker.io/nginx
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent 
