apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: altair
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Talha-Altair/argocd-base.git
    targetRevision: HEAD
    path: altair
    helm:
      valueFiles:
      - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: altair

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
