apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proj
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:Talha-Altair/argocd-base.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
