apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ghcr.io/talha-altair/tva:latest
        ports:
        - containerPort: 8500
        envFrom:
        - configMapRef:
            name: random2
        imagePullPolicy: Always 
